{"uuid": "20a47544-ace4-4de4-ae10-036123f42310", "children": ["543b3c83-0319-4c5a-99f2-a8dff7609f32"], "befores": [{"name": "set_up", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"C:\\Users\\king natan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\king natan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\king natan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\king natan\\PycharmProjects\\while\\Class_Selenium_Project\\Base\\base.py\", line 9, in set_up\n    self.driver = webdriver.Chrome(\"..//Drivers/chromedriver.exe\")\n  File \"C:\\Users\\king natan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 70, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"C:\\Users\\king natan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 90, in __init__\n    self.service.start()\n  File \"C:\\Users\\king natan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1652544351445, "stop": 1652544351450}], "start": 1652544351445, "stop": 1652544351598}